# Generated by Django 4.1.2 on 2022-10-26 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vacantes.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=56, null=True)),
                ('ruta_foto', models.URLField(default='http://127.0.0.1:8000/media/imagenes/b51e0317-4e30-11ed-8d20-c80c0051d672.jpg')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('titulo_personal', models.CharField(blank=True, max_length=60, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=90)),
                ('pais', models.CharField(max_length=30)),
                ('correo_vacantes', models.EmailField(max_length=60)),
                ('descripcion_empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('url_web', models.URLField(blank=True, max_length=100, null=True)),
                ('url_facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('url_instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('url_twitter', models.URLField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=vacantes.functions.image_upload_location)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=50)),
                ('tipo_trabajo', models.CharField(choices=[('TEMPORAL', 'Temporal'), ('INDEFINIDO', 'Indefinido')], default='TEMPORAL', max_length=10)),
                ('forma_trabajo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Hibrido'), ('REMOTO', 'Remoto')], default='PRESENCIAL', max_length=10)),
                ('experiencia', models.BooleanField()),
                ('responsabilidades_puesto', models.TextField(blank=True, null=True)),
                ('requisitos_obligatorios', models.TextField()),
                ('requisitos_opcionales', models.TextField(blank=True, null=True)),
                ('salario_min', models.IntegerField(blank=True, null=True)),
                ('salario_max', models.IntegerField(blank=True, null=True)),
                ('beneficios', models.TextField(blank=True, null=True)),
                ('horario_trabajo', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='VacantesGuardadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('cv_url', models.URLField(default='http://127.0.0.1:8000/media/cv/f37aca8b-4b2b-11ed-8a6f-c80c0051d672-Nita_Ditch.pdf')),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.candidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
        ),
    ]
