# Generated by Django 4.1.2 on 2022-10-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dirección', models.CharField(max_length=90)),
                ('pais', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=60)),
                ('correo_vacantes', models.EmailField(max_length=60)),
                ('descripcion_empresa', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=13)),
                ('url_web', models.URLField(blank=True, max_length=100, null=True)),
                ('url_facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('url_instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('url_twitter', models.URLField(blank=True, max_length=100, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='vacantes/imagenes/empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=50)),
                ('tipo_trabajo', models.CharField(choices=[('TEMPORAL', 'Temporal'), ('INDEFINIDO', 'Indefinido')], default='TEMPORAL', max_length=10)),
                ('forma_trabajo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Hibrido'), ('REMOTO', 'Remoto')], default='PRESENCIAL', max_length=10)),
                ('experiencia', models.BooleanField()),
                ('responsabilidades_puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos_obligatorios', models.CharField(max_length=200)),
                ('requisitos_obcionales', models.CharField(max_length=200)),
                ('salario_min', models.IntegerField()),
                ('salario_max', models.IntegerField()),
                ('beneficios', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_trabajo', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.candidato')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
        ),
    ]
