# Generated by Django 4.1.2 on 2022-10-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='requisitos_opcionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salario_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
