# Generated by Django 4.1.2 on 2022-10-26 02:16

from django.db import migrations, models
import vacantes.functions


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='ruta_foto',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=vacantes.functions.image_upload_location),
        ),
    ]
