# Generated by Django 4.1.2 on 2022-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_candidato_empresa_vacante_solicitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='vacante',
            old_name='categoría',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='vacante',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
