# Generated by Django 4.1.2 on 2022-10-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_remove_candidato_ruta_foto_candidato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion_empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='url_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='url_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='url_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='url_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
