# Generated by Django 4.1.2 on 2022-10-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_rename_dirección_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacante',
            old_name='requisitos_obcionales',
            new_name='requisitos_opcionales',
        ),
    ]
