# Generated by Django 4.1.2 on 2022-10-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0003_remove_candidato_correo_candidato_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ruta_foto',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/media/imagenes/b51e0317-4e30-11ed-8d20-c80c0051d672.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='cv_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/media/cv/f37aca8b-4b2b-11ed-8a6f-c80c0051d672-Nita_Ditch.pdf', null=True),
        ),
    ]
