# Generated by Django 4.1.2 on 2022-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_alter_candidato_ruta_foto_alter_solicitude_cv_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='cv_url',
            field=models.URLField(default='http://127.0.0.1:8000/media/cv/f37aca8b-4b2b-11ed-8a6f-c80c0051d672-Nita_Ditch.pdf'),
        ),
    ]
