# Generated by Django 4.1.2 on 2022-10-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_rename_requisitos_obcionales_vacante_requisitos_opcionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos_obligatorios',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requisitos_opcionales',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='responsabilidades_puesto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
