# Generated by Django 4.1.2 on 2022-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_alter_solicitude_mensaje_alter_vacante_beneficios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cv',
            field=models.ImageField(blank=True, null=True, upload_to='curriculums'),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='cv',
            field=models.FilePathField(blank=True, null=True, path='curriculums'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/empresas'),
        ),
    ]
