# Generated by Django 4.1.2 on 2022-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_alter_solicitude_cv_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='ruta_foto',
            field=models.URLField(default='http://127.0.0.1:8000/media/imagenes/b51e0317-4e30-11ed-8d20-c80c0051d672.jpg'),
        ),
    ]
