# Generated by Django 4.1.2 on 2022-10-25 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0006_alter_candidato_ruta_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='correo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
