# Generated by Django 4.1.2 on 2022-10-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0006_candidato_cv_solicitude_cv_alter_empresa_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitude',
            old_name='cv',
            new_name='cv_candidato',
        ),
    ]
