# Generated by Django 4.1.2 on 2022-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0007_rename_cv_solicitude_cv_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='curriculums'),
        ),
    ]
