# Generated by Django 4.1.2 on 2022-10-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0008_alter_candidato_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='solicitude',
            name='cv_candidato',
        ),
        migrations.RemoveField(
            model_name='vacante',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitude',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
