# Generated by Django 4.1.2 on 2022-10-13 14:24

from django.db import migrations, models
import vacantes.functions


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0009_remove_candidato_cv_remove_solicitude_cv_candidato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=vacantes.functions.file_upload_location),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='candidato_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitude',
            name='cv_candidato',
            field=models.FilePathField(blank=True, null=True, path=models.CharField(blank=True, max_length=100, null=True)),
        ),
    ]
