# Generated by Django 4.1.2 on 2022-10-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0011_remove_solicitude_candidato_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='cv_candidato',
            field=models.URLField(blank=True, null=True),
        ),
    ]
