# Generated by Django 4.1.2 on 2022-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0012_alter_solicitude_cv_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitude',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
