# Generated by Django 4.1.2 on 2022-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0013_alter_solicitude_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='solicitude',
            name='cv_candidato',
        ),
        migrations.AddField(
            model_name='solicitude',
            name='cv',
            field=models.FilePathField(blank=True, null=True, path='cv/f37aca8b-4b2b-11ed-8a6f-c80c0051d672-Nita_Ditch.pdf'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
