# Generated by Django 4.1.2 on 2022-10-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0014_remove_candidato_cv_remove_solicitude_cv_candidato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitude',
            name='cv',
        ),
        migrations.AddField(
            model_name='solicitude',
            name='cv_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/media/cv/f37aca8b-4b2b-11ed-8a6f-c80c0051d672-Nita_Ditch.pdf', null=True),
        ),
    ]
